### ISSUE TITLE
Nightly build 0.6.2-20201210.1 failed to start with exception

### ISSUE THREAD

**Issue by gnozil** [TheGoddessInari/hamsket#246]
https://github.com/TheGoddessInari/hamsket/releases/download/0.6.2/hamsket_0.6.2_amd64.deb published in Dec 11 has problem:

$ md5sum hamsket_0.6.2_amd64.deb 
f4c990b5c32d889e8071e77c2a6927b7  hamsket_0.6.2_amd64.deb

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-is-dev'
Require stack:
- /opt/Hamsket/resources/app.asar/electron/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/opt/Hamsket/resources/app.asar/electron/main.js:11:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)

**Comment by TheGoddessInari** [comment]
Eh, that was republished yesterday. Try redownloading it again. git commit should read as 7bbb2c6a0dfb064af080a66c516c281da886eb83 in About.

**Comment by gnozil** [comment]
I checked https://github.com/TheGoddessInari/hamsket/tags, the latest tag is fd10375.

**Comment by gnozil** [comment]
So now I have to backed to 0.6.0, and I found 0.6.0 has two places are better than 0.6.1 or discarded 0.6.2:

1. I preferred to use layout with Hamsket service bar in left side without names. In 0.6.0, there is not a separator between left bar and right panel. But in later 0.6.1 and discarded 0.6.2, there is a deep blue separator line

2. In office 365 outlook App SSO login page, the cursor is blink in the username/password text box in 0.6.0. But no cursor in later releases.

**Comment by LiBOSS-CZ** [comment]
I have just tried and fd10375 works

**Comment by chwba** [comment]
Its still broken, on Windows as well, same error with the current windows  installer (nightly).

**Comment by devprjgithub** [comment]
Latest on master 011ded4 still has this issue.
fd10375  "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." Will it be released on branch?

**Comment by gnozil** [comment]
> I checked https://github.com/TheGoddessInari/hamsket/tags, the latest downloadable tag is [fd10375](https://github.com/TheGoddessInari/hamsket/commit/fd1037521df6214a1b6b3751242cfa409c4ac236).

fd10375 works well. Thanks.

**Comment by devprjgithub** [comment]
Try do fresh "git clone https://github.com/TheGoddessInari/hamsket.git" You will not get "fd10375" As I mentioned  "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."  You see this message on github on top of screen of this commit.

**Comment by devprjgithub** [comment]
Oops. I got it.
